name: Tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  required:
    runs-on: ubuntu-latest
    name: ubuntu / stable
    steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: cargo test -v --no-fail-fast
